# Generated by Django 4.1.4 on 2024-07-16 08:19

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activitytestimonial_alter_destination_options_and_more'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=500)),
                ('email', models.CharField(blank=True, max_length=500)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(upload_to='')),
                ('image_alt_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='NewsletterSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ('order', 'name')},
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='meta_description',
            field=models.TextField(default='Meta Description Landing Page'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='meta_title',
            field=models.CharField(default='Meta Title Landing Page', max_length=200),
        ),
        migrations.AddField(
            model_name='teammember',
            name='order',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='source',
            field=models.CharField(choices=[('Trip Advisor', 'Trip Advisor'), ('Trust Pilot', 'Trust Pilot'), ('Google', 'Google'), ('Others', 'Others')], default='Others', max_length=200),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='about',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.CreateModel(
            name='FeaturedTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_tour', models.ManyToManyField(blank=True, related_name='banner_tour', to='activity.activity')),
                ('best_selling_tours', models.ManyToManyField(blank=True, limit_choices_to={'best_selling': True}, related_name='best_selling_tours', to='activity.activity')),
                ('favourite_tours', models.ManyToManyField(blank=True, related_name='favourite_tours', to='activity.activity')),
                ('featured_tours', models.ManyToManyField(blank=True, limit_choices_to={'featured': True}, related_name='featured_tours', to='activity.activity')),
                ('popular_tours', models.ManyToManyField(blank=True, limit_choices_to={'popular': True}, related_name='popular_tours', to='activity.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
